apiVersion: v1
kind: Template
parameters:
- name: IMAGE_TAG
  required: true
- name: REPO_NAME
  value: REPLACED_BY_SCRIPT
  required: true
- name: IDENTITY_ATTR_EMAIL
  required: true
- name: IDENTITY_ATTR_ID
  required: true
- name: IDENTITY_ATTR_NAME
  required: true
- name: IDENTITY_ATTR_PREFERRED_USERNAME
  required: true
- name: IDENTITY_BIND_DN
  required: true
- name: IDENTITY_URL
  required: true
- name: IDENTITY_SRE_GOOGLE_CLIENTID
  required: true
- name: IDENTITY_NAME
  required: true
- name: IDENTITY_MAPPING_METHOD
  required: true
- name: TELEMETER_SERVER_URL
  required: true
- name: CS_SRE_USERS
  required: true
- name: CEE_USERS
  required: true
- name: SREP_USERS
  required: true
- name: OCM_BASE_URL
  required: true
- name: SREP_LEGAL_ENTITY_ID
  required: true
- name: OBSERVATORIUM_LEGALENTITY_IDS
  required: true
metadata:
  name: selectorsyncset-template
objects:
# the SelectorSyncIdentityProvider is not something you can oc apply in-cluster, so is not created in `deploy/`
- apiVersion: hive.openshift.io/v1
  kind: SelectorSyncIdentityProvider
  metadata:
    name: osd-sre-identityprovider
  spec:
    clusterDeploymentSelector:
      matchLabels:
        api.openshift.com/managed: "true"
      matchExpressions:
        - key: api.openshift.com/environment
          operator: NotIn
          values:
          - "production"
    identityProviders:
    - challenge: true
      ldap:
        attributes:
          email:
          - ${IDENTITY_ATTR_EMAIL}
          id:
          - ${IDENTITY_ATTR_ID}
          name:
          - ${IDENTITY_ATTR_NAME}
          preferredUsername:
          - ${IDENTITY_ATTR_PREFERRED_USERNAME}
        bindDN: ${IDENTITY_BIND_DN}
        bindPassword:
          name: osd-ldap-secret
        ca:
          name: osd-ldap-ca-configmap
        insecure: false
        url: ${IDENTITY_URL}
      login: true
      mappingMethod: ${IDENTITY_MAPPING_METHOD}
      name: ${IDENTITY_NAME}
      type: LDAP
# SelectorSyncIdentityProvider for prod clusters
- apiVersion: hive.openshift.io/v1
  kind: SelectorSyncIdentityProvider
  metadata:
    name: osd-sre-google-identityprovider
  spec:
    clusterDeploymentSelector:
      matchLabels:
        api.openshift.com/managed: "true"
        api.openshift.com/environment: "production"
    identityProviders:
    - google:
        clientID: ${IDENTITY_SRE_GOOGLE_CLIENTID}
        clientSecret:
          name: osd-google-secret
        hostedDomain: redhat.com
      mappingMethod: claim
      name: OpenShift_SRE
      type: Google
# SelectorSyncSet for observatorium token refresher credentials Secret
- apiVersion: hive.openshift.io/v1
  kind: SelectorSyncSet
  metadata:
    name: osd-observatorium-credentials-secret
  spec:
    clusterDeploymentSelector:
      matchExpressions:
      - key: api.openshift.com/managed
        operator: In
        values:
        - "true"
    resourceApplyMode: Sync
    secretMappings:
    - sourceRef:
        name: observatorium-credentials
        namespace: observatorium-tenant
      targetRef:
        name: observatorium-credentials
        namespace: openshift-monitoring
