---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: osd-logging-freeze
  namespace: openshift-logging
rules:
- apiGroups:
  - operators.coreos.com
  resources:
  - subscriptions
  verbs:
  - patch
  - get
  - list
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
