---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: osd-logging-freeze
  namespace: openshift-logging
subjects:
- kind: ServiceAccount
  name: osd-logging-freeze
  namespace: openshift-logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: osd-logging-freeze
  namespace: openshift-logging
