apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-infra-node-imbalance
    role: alert-rules
  name: sre-infra-node-imbalance
  namespace: openshift-monitoring
spec:
  groups:
  - name: sre-infra-node-imbalance
    rules:
    - alert: KubeInfraNodeImbalanceSRE
      expr: count(count by (node) (kube_pod_info{namespace="openshift-monitoring",pod=~"prometheus-k8s-.*"})) < 2
      for: 1h
      labels:
        severity: warning
        namespace: openshift-monitoring
      annotations:
        message: "The infra node prometheus scheduling has been imbalanced for more than an hour."
        link: "https://github.com/openshift/ops-sop/blob/master/v4/alerts/KubeInfraNodeImbalanceSRE.md"
