kind: ClusterResourceQuota
apiVersion: quota.openshift.io/v1
metadata:
  name: persistent-volume-quota
spec:
  selector:
    annotations: null
    labels:
      matchExpressions:
      - key: managed.openshift.io/storage-pv-quota-exempt
        operator: DoesNotExist
  quota:
    hard:
      gp2.storageclass.storage.k8s.io/requests.storage: 3600Gi
